package com.openai.codexmobile.ui

object TestTags {
    const val ConnectionScreen = "connection_screen"
    const val ConnectionEndpointField = "connection_endpoint_field"
    const val ConnectionConnectButton = "connection_connect_button"
    const val ConnectionOpenSettingsButton = "connection_open_settings_button"

    const val SessionListScreen = "session_list_screen"
    const val SessionListCreateButton = "session_list_create_button"
    const val SessionListCreateDraftButton = "session_list_create_draft_button"
    const val SessionListOpenSettingsButton = "session_list_open_settings_button"
    const val SessionListDisconnectButton = "session_list_disconnect_button"
    const val SessionListItemPrefix = "session_list_item_"
    const val SessionListFolderPrefix = "session_list_folder_"
    const val SessionListFolderCreatePrefix = "session_list_folder_create_"
    const val SessionListCreateDialog = "session_list_create_dialog"
    const val SessionListDraftDirectoryField = "session_list_draft_directory_field"
    const val SessionListDraftDialogConfirmButton = "session_list_draft_dialog_confirm_button"

    const val SessionDetailScreen = "session_detail_screen"
    const val SessionDetailTranscript = "session_detail_transcript"
    const val SessionDetailDraftField = "session_detail_draft_field"
    const val SessionDetailAttachImageButton = "session_detail_attach_image_button"
    const val SessionDetailPendingImageCard = "session_detail_pending_image_card"
    const val SessionDetailClearImageButton = "session_detail_clear_image_button"
    const val SessionDetailSendButton = "session_detail_send_button"
    const val SessionDetailBackButton = "session_detail_back_button"
    const val SessionDetailStatusStrip = "session_detail_status_strip"
    const val SessionDetailStatusButton = "session_detail_status_button"
    const val SessionDetailStatusDetails = "session_detail_status_details"
    const val SessionDetailStatusRefreshButton = "session_detail_status_refresh_button"
    const val SessionDetailConfigRow = "session_detail_config_row"
    const val SessionDetailConfigModelButton = "session_detail_config_model_button"
    const val SessionDetailConfigReasoningButton = "session_detail_config_reasoning_button"
    const val SessionDetailConfigServiceTierButton = "session_detail_config_service_tier_button"
    const val SessionDetailConfigSandboxButton = "session_detail_config_sandbox_button"
    const val SessionDetailConfigCwdButton = "session_detail_config_cwd_button"
    const val SessionDetailTranscriptScroll = "session_detail_transcript_scroll"
    const val SessionDetailTranscriptBubbleTogglePrefix = "session_detail_transcript_bubble_toggle_"
    const val SessionDetailExecutionGroupTogglePrefix = "session_detail_execution_group_toggle_"
    const val SessionDetailExecutionEntryTogglePrefix = "session_detail_execution_entry_toggle_"
    const val SessionDetailApprovalCard = "session_detail_approval_card"
    const val SessionDetailApprovalSummary = "session_detail_approval_summary"
    const val SessionDetailQueuedInputsCard = "session_detail_queued_inputs_card"
    const val SessionDetailApproveButton = "session_detail_approve_button"
    const val SessionDetailApproveForSessionButton = "session_detail_approve_for_session_button"
    const val SessionDetailRejectButton = "session_detail_reject_button"
    const val SessionDetailRejectAndInterruptButton = "session_detail_reject_and_interrupt_button"

    const val SettingsScreen = "settings_screen"
    const val SettingsEndpointField = "settings_endpoint_field"
    const val SettingsAuthTokenField = "settings_auth_token_field"
    const val SettingsCwdField = "settings_cwd_field"
    const val SettingsModelField = "settings_model_field"
    const val SettingsReasoningMinimalButton = "settings_reasoning_minimal_button"
    const val SettingsReasoningLowButton = "settings_reasoning_low_button"
    const val SettingsReasoningMediumButton = "settings_reasoning_medium_button"
    const val SettingsReasoningHighButton = "settings_reasoning_high_button"
    const val SettingsReasoningXHighButton = "settings_reasoning_xhigh_button"
    const val SettingsServiceDefaultButton = "settings_service_default_button"
    const val SettingsServiceFastButton = "settings_service_fast_button"
    const val SettingsSandboxReadOnlyButton = "settings_sandbox_read_only_button"
    const val SettingsSandboxWorkspaceWriteButton = "settings_sandbox_workspace_write_button"
    const val SettingsSandboxDangerButton = "settings_sandbox_danger_button"
    const val SettingsApprovalManualButton = "settings_approval_manual_button"
    const val SettingsApprovalAutoButton = "settings_approval_auto_button"
    const val SettingsRefreshLogsButton = "settings_refresh_logs_button"
    const val SettingsClearLogsButton = "settings_clear_logs_button"
    const val SettingsCopyLogsButton = "settings_copy_logs_button"
    const val SettingsLogsCard = "settings_logs_card"
    const val SettingsBackButton = "settings_back_button"
}
